# Workflow version v0.1.2, workflow subs: [name: `Sailboat`, short_name: `sailboat`]
name: Publish release files for Sailboat.

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_path: ./dist/*/*
            builds:  homebrew pyinstaller pypi
            asset_name: default
            glob: true

          - os: windows-latest
            builds:  pyinstaller
            artifact_path: .\dist\*\*
            asset_name: default
            glob: true

          - os: macos-latest
            builds:  pyinstaller
            artifact_path: ./dist/*/*
            asset_name: default
            glob: true

# ===================== EDIT AT YOUR OWN RISK ============================================
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies and Build
      run: |
        pip install sailboat
        python -m sailboat.__main__ build + ${{ matrix.builds }}
        
    - name: Check for prerelease
      run: python -m sailboat.prerelease ${{ github.ref }} >> $GITHUB_ENV

    - name: Upload binaries to prerelease
      if: env.prerel == 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_path }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        file_glob: ${{ matrix.glob }}
        body: ${{ github.event.head_commit.message }}
        prerelease: true
      
    - name: Upload binaries to production release
      if: env.prerel != 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_path }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        file_glob: ${{ matrix.glob }}
        body: ${{ github.event.head_commit.message }}
        prerelease: false