name: Publish system files for ShipSnake.

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_path: .\dist\pypi\*.whl
            asset_name: ShipSnake-pypi-wheel.whl
						glob: true
          - os: windows-latest
            artifact_path: .\dist\pyinstaller\ShipSnake.exe
            asset_name: ShipSnake-windows.exe
						glob: false
          - os: macos-latest
            artifact_path: ./dist/pyinstaller/ShipSnake.dmg
            asset_name: ShipSnake-mac.dmg
						glob: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Install Dependencies and Build
      run: |
        pip install shipsnake
        python -m shipsnake.actions
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_path }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
				file_glob: ${{ matrix.glob }}
